### ISSUE TITLE
Compatibility with port and path needed

### ISSUE THREAD

**Issue by mightyspiky** [plan44/localSites#1]
I would like very much to see compatibility with port and path implemented. Right now, http://server.local:port/absolute/path becomes http://server.local so most of my Bonjour sites don't work.

**Comment by plan44** [comment]
Thanks for the feedback!

Yes, the *path* part is missing - I never had bonjour services using that, but I see now it's [part of the spec](http://www.dns-sd.org/txtrecords.html) - I will add it right now.

However figuring out the port *should* be part of resolving the address in the browser, which means that `.local.` dns-sd hostnames must *not* have a `:port` suffix.

I tested this with Safari/Firefox/Chrome and all three correctly resolve a `local.` url without port specification to the right server *and* non-standard port number (and only Chrome does not fail if the `:port` is in the url)

On the other hand, all three browsers *also* succeed when passed an url without the trailing dot, but including the port number. Even if this is [technically incorrect](http://www.dns-sd.org/trailingdotsindomainnames.html), it seems to be the approach that is more compatible. The next version of LocalSites (v1.1, on its way) will do it that way.

**Comment by mightyspiky** [comment]
Now, all my Bonjour sites are working. Wow, that was fast 👍 .

When the app will be updated on the app store, I will be happy to review it five stars. Big thanks man!!
