### ISSUE TITLE
Support for El Capitan

### ISSUE THREAD

**Issue by JayBrown** [plan44/localSites#2]
Safari 11 is for OS X 10.11.6 and above, so a version with support for El Capitan would be great. I'll try building this myself as well, but maybe there are users out there without Xcode who'd want it for El Capitan.

EDIT: nope… can't build, no codesigning certificate for entitlements, SWIFT syntax mismatch etc.

**Comment by plan44** [comment]
No worries, I'm updating the app to make it run under 10.11 ;-)
Regarding compiling: the app is written in Swift 4, which means you need the latest XCode 9.

**Comment by JayBrown** [comment]
Now released.
