### ISSUE TITLE
Open at login

### ISSUE THREAD

**Issue by JayBrown** [plan44/localSites#3]
For your information: there's a Swift framework here, safe for Mac App Store, apparently

https://github.com/inket/StartAtLogin

**Comment by plan44** [comment]
Thanks for the hint - I will consider using it for a future version.
For the time being, you can add the app manually to "login items" via System Preferences -> Users&Groups

**Comment by plan44** [comment]
Reading the above again years later, I decided to close the issue. Yes, StartAtLogin looks nice, but it also means adding a dependency, which always has potential to complicate long term (we're approaching the decade here) maintainance. And minimizing maintainance is paramount for keeping little side projects like this alive ;-)
