### ISSUE TITLE
Full Bonjour info possible?

### ISSUE THREAD

**Issue by JayBrown** [plan44/localSites#4]
Is it possible to update the app to show all bonjour services with full info? For example, after the "Open in default browser" list, there would be another separator, and then a full list (or a submenu with the full list) of every service available locally and remotely, tcp & udp, localhost, LAN, v4, v6, via ssh tunnels etc., similar to what Bonjour browsers do.

I know that's not the intended app functionality, but maybe you can add an in-app Pro purchase option in a future update for people who want full Bonjour overview functionality. :)

**Comment by plan44** [comment]
I think that's a bit out of scope for this simple menubar app. I also use bonjour beyond http myself, but for that I fire up [Kevin Ballard's "Bonjour Browser"](http://www.tildesoft.com) (quite old, but still working fine on 10.13). And fortunately, unlike Safari 11, Terminal has not lost its Bonjour support.

**Comment by JayBrown** [comment]
I understand completely. Kevin's software will eventually stop working, because it's i386 only, but another software (same name) still seems to be under development, incl. HomeKit support as the latest addition: https://sourceforge.net/projects/bonjourbrowser/

**Comment by plan44** [comment]
Years later, JFYI: former "Bonjour Browser" did **not stop working** and has been updated in 2021 to universal x86/ARM binary. It has been renamed "Discovery", is maintained by tildesoft/Lily Ballard, and is still [in the Mac App Store](https://apps.apple.com/ch/app/discovery-dns-sd-browser/id1381004916). I use it a lot while working on my matter bridge and need to see beyond `_http._tcp`. I prefer the simple single-panel treeview where I can expand and watch multiple nodes' details at once.
